### ISSUE TITLE
Infinite loop when requesting ElasticSearch

### ISSUE THREAD

**Issue by dayman** [pyr/cyanite#105]
I use REST driver to connect to ES

```
index:
  use: "io.cyanite.es_path/es-rest"
  index: "cyanite_paths"
  url: "http://elastic_host:9200"
  chan_size: 10000
  batch_size: 1000
```
when I perform request 
```
curl http://cyanite_host:8080/paths?query=servers
```
it fails due to timeout.

With tcpdump I sniffed the traffic going from cyanite to ES and discovered that it first requests
```
 /cyanite_paths HTTP/1.1
```
and then starts "DOSing" Elastic Search with endless chain of identical requests  
```
/_search/scroll?scroll_id=cXVlcnlUaGVuRmV0Y2g7NTsxODk6emNnTUMtdkdRSldSUHctdUdWVi1IZzsyNDE6Wm55TkRwcXBSSDZjU0VJb1czdHlyUTsxOTE6emNnTUMtdkdRSldSUHctdUdWVi1IZzsxODc6OGFlV2VsWUdUWENtT0kzRWZGVEFsQTsxOTA6emNnTUMtdkdRSldSUHctdUdWVi1IZzswOw%3D%3D
```
I think its the same mentioned in https://github.com/pyr/cyanite/issues/97

I use ES 1.4.4

I presume response that /scroll request returns is
```
{"_index":"cyanite_paths","_type":"_search","_id":"scroll","found":false}
```
