### ISSUE TITLE
project flux - current config

### ISSUE THREAD

**Issue by danielsand** [pyr/cyanite#112]
Hey Pyr,

great project - but you're currently changing a lot and I try to set it up. 
Im currently struggling a lot on this.

looks like you changed in the last week the configuration yaml.

My current problem is that the carbon listener not comes up. 

i grep for the ports and its odd that he now picks port 80 for api and 2002 should be not carbon.
````
root@cyanite:/var/log/cyanite# netstat -tlapn|grep LISTEN
tcp        0      0 0.0.0.0:80              0.0.0.0:*               LISTEN      16851/java
tcp        0      0 127.0.0.1:2002          0.0.0.0:*               LISTEN      16851/java
```
/etc/cyanite.yaml
```
logging:
  level: debug
  console: false
  files:
    - "/var/log/cyanite/cyanite.log"
store:
  type: "cassandra-v2"
  cluster: "127.0.0.1"
index:
  type: "memory"
http:
  host: "0.0.0.0"
  port: "8080"
carbon:
  host: "0.0.0.0"
  port: "2003"
engine:
  rules:
    default:
      - "5s:1h"
```

start command:
```
java -Djava.net.preferIPv4Stack=true -jar /mnt/cyanite/cyanite-0.5.1-standalone.jar -f /etc/cyanite.yaml
````

i builded all with oracle jdk 1.8

if you have some keen eyes and see the problem - please help :)

**Comment by danielsand** [comment]
oh btw - i see no errors in the log.

and already tried the default yaml config.

**Comment by pyr** [comment]
Hi @danielsand,

Sorry about the big changes. Since yesterday, the configuration format has changed. I plan to add more elaborate docs around this very quickly now.

The format that is now relevant is the following:

```yaml
### logging adheres to the rules as defined in https://github.com/pyr/unilog
logging:
  level: info
  console: true
  files:
    - "/var/log/cyanite/cyanite.log"
##
## engine
## =====
## The only option for the engine is "rules" for now, a map which keys may be
## a regexp pattern or "default" and an associated list of resolutions consisting
## of <precision>:<period>
engine:
  rules:
    default: [ "5s:1h" ]
## inputs
## ====
##
## inputs are a list of maps which need at least a 
## "type" field.
## Current valid inputs are: "carbon" and "pickle", which
## both accept a port key
input:
  - type: carbon
api:
  port: 8080
##
## index
## ====
##
## Indices are needed to store path names and retrieve them efficiently.
## Two options are available for now: "memory" and "elasticsearch|
##
index:
  type: elasticsearch
  url: http://localhost:9200/cyanite
  index: path
##
## store
## ====
## stores store your metrics, they dispatch on "type" too,
## but the only valid one for production usage is "cassandra"
store:
  cluster: 'localhost'
  keyspace: 'metric'
```

**Comment by joshpollara** [comment]
I have the same problem and I tried the config above. No luck.

**Comment by pyr** [comment]
@joshpollara which build did you try it with ?

**Comment by joshpollara** [comment]
cyanite-0.5.1-standalone.jar.... I just cloned master a few minutes ago and tried again.

usvagijpsbx01: ~ ⇒  ps faux | grep cyanite
jpollara 21575 24.5  6.4 3574428 249672 pts/0  Sl+  15:16   0:10          \_ java -jar /home/jpollara/cyanite/target/cyanite-0.5.1-standalone.jar
jpollara 21665  0.0  0.0 110404   864 pts/1    S+   15:17   0:00              \_ grep --color cyanite
usvagijpsbx01: ~ ⇒  netstat -tunap | grep 21575
(Not all processes could be identified, non-owned process info
 will not be shown, you would have to be root to see it all.)
tcp        0      0 :::8080                     :::*                        LISTEN      21575/java
tcp        0      0 ::ffff:127.0.0.1:2002       :::*                        LISTEN      21575/java
tcp        0      0 ::ffff:127.0.0.1:49687      ::ffff:127.0.0.1:9200       ESTABLISHED 21575/java
tcp        0      0 ::ffff:127.0.0.1:36611      ::ffff:127.0.0.1:9042       ESTABLISHED 21575/java
tcp        0      0 ::ffff:127.0.0.1:36612      ::ffff:127.0.0.1:9042       ESTABLISHED 21575/java
usvagijpsbx01: ~ ⇒

**Comment by pyr** [comment]
@joshpollara with the above config can you share the output of `java -jar target/cyanite-0.5.1-standalone.jar -f cyanite.yaml` ? What version of the JDK do you run it with ?

**Comment by joshpollara** [comment]
usvagijpsbx01: ~ ⇒  java -version
java version "1.8.0_20"
Java(TM) SE Runtime Environment (build 1.8.0_20-b26)
Java HotSpot(TM) 64-Bit Server VM (build 25.20-b23, mixed mode)
usvagijpsbx01: ~ ⇒  java -jar /home/jpollara/cyanite/target/cyanite-0.5.1-standalone.jar -f /etc/cyanite.yaml
15:34:38.151 [main] DEBUG org.eclipse.jetty.util.log - Logging to Logger[org.eclipse.jetty.util.log] via org.eclipse.jetty.util.log.Slf4jLog
15:34:38.160 [main] INFO  org.eclipse.jetty.util.log - Logging initialized @2063ms
15:34:40.046 [main] DEBUG c.d.driver.core.SystemProperties - com.datastax.driver.NEW_NODE_DELAY_SECONDS is undefined, using default value 1
15:34:40.047 [main] DEBUG c.d.driver.core.SystemProperties - com.datastax.driver.NON_BLOCKING_EXECUTOR_SIZE is undefined, using default value 2
15:34:40.048 [main] DEBUG c.d.driver.core.SystemProperties - com.datastax.driver.NOTIF_LOCK_TIMEOUT_SECONDS is undefined, using default value 60
15:34:40.158 [main] DEBUG i.n.u.i.l.InternalLoggerFactory - Using SLF4J as the default logging framework
15:34:40.163 [main] DEBUG i.n.util.internal.PlatformDependent0 - java.nio.Buffer.address: available
15:34:40.164 [main] DEBUG i.n.util.internal.PlatformDependent0 - sun.misc.Unsafe.theUnsafe: available
15:34:40.165 [main] DEBUG i.n.util.internal.PlatformDependent0 - sun.misc.Unsafe.copyMemory: available
15:34:40.165 [main] DEBUG i.n.util.internal.PlatformDependent0 - java.nio.Bits.unaligned: true
15:34:40.167 [main] DEBUG i.n.util.internal.PlatformDependent - Java version: 8
15:34:40.167 [main] DEBUG i.n.util.internal.PlatformDependent - -Dio.netty.noUnsafe: false
15:34:40.168 [main] DEBUG i.n.util.internal.PlatformDependent - sun.misc.Unsafe: available
15:34:40.168 [main] DEBUG i.n.util.internal.PlatformDependent - -Dio.netty.noJavassist: false
15:34:40.169 [main] DEBUG i.n.util.internal.PlatformDependent - Javassist: unavailable
15:34:40.169 [main] DEBUG i.n.util.internal.PlatformDependent - You don't have Javassist in your class path or you don't have enough permission to load dynamically generated classes.  Please check the configuration for better performance.
15:34:40.169 [main] DEBUG i.n.util.internal.PlatformDependent - -Dio.netty.tmpdir: /tmp (java.io.tmpdir)
15:34:40.169 [main] DEBUG i.n.util.internal.PlatformDependent - -Dio.netty.bitMode: 64 (sun.arch.data.model)
15:34:40.170 [main] DEBUG i.n.util.internal.PlatformDependent - -Dio.netty.noPreferDirect: false
starting with configuration:  /etc/cyanite.yaml
INFO [2015-07-28 15:34:40,578] main - io.cyanite installing signal handlers
INFO [2015-07-28 15:34:40,581] main - io.cyanite ready to start system
INFO [2015-07-28 15:34:40,660] main - com.datastax.driver.core.NettyUtil Did not find Netty's native epoll transport in the classpath, defaulting to NIO.
INFO [2015-07-28 15:34:41,650] main - com.datastax.driver.core.policies.DCAwareRoundRobinPolicy Using data-center name 'datacenter1' for DCAwareRoundRobinPolicy (if this is incorrect, please provide the correct datacenter name with DCAwareRoundRobinPolicy constructor)
INFO [2015-07-28 15:34:41,651] main - com.datastax.driver.core.Cluster New Cassandra host localhost/127.0.0.1:9042 added
INFO [2015-07-28 15:34:42,501] main - io.cyanite.engine starting engine
INFO [2015-07-28 15:34:42,628] claypoole-2-0 - org.eclipse.jetty.server.Server jetty-9.3.z-SNAPSHOT
INFO [2015-07-28 15:34:42,639] claypoole-2-0 - org.eclipse.jetty.server.ServerConnector Started ServerConnector@6793a9a1{HTTP/1.1,[http/1.1]}{0.0.0.0:8080}
INFO [2015-07-28 15:34:42,645] claypoole-2-0 - org.eclipse.jetty.server.Server Started @6548ms

**Comment by pyr** [comment]
@joshpollara This actually looks right, you should have a listening port 2002 (which is a mistake, I know)

**Comment by joshpollara** [comment]
OK cool. Unfortunately when I try to submit a metric I get an error:

DEBUG [2015-07-28 15:42:00,174] claypoole-1-3 - io.cyanite.engine in write callback:  #io.cyanite.engine.buckets.MetricSnapshot{:path "jp.foo", :time 1438112515, :mean 15163.6, :max 24741.0, :min 4874.0, :sum 75818.0, :resolution #io.cyanite.engine.rule.Resolution{:precision 5, :period 3600}}
WARN [2015-07-28 15:42:00,184] claypoole-1-3 - io.cyanite.engine.queue could not process element on queue 3 for :writeq
java.lang.NullPointerException: null
	at qbits.alia.codec.udt$encoder$fn__423.invoke(udt.clj:116) ~[cyanite-0.5.1-standalone.jar:na]
	at io.cyanite.store.cassandra$get_types$fn__7374.invoke(cassandra.clj:82) ~[cyanite-0.5.1-standalone.jar:na]
	at io.cyanite.store.CassandraV2Store.insert_BANG_(store.clj:54) ~[cyanite-0.5.1-standalone.jar:na]
	at io.cyanite.engine.Engine$fn__9672.invoke(engine.clj:44) ~[cyanite-0.5.1-standalone.jar:na]
	at io.cyanite.engine.queue$queue_engine$reify__7982$future_body__7983$fn__7984.invoke(queue.clj:33) ~[cyanite-0.5.1-standalone.jar:na]
	at io.cyanite.engine.queue$queue_engine$reify__7982$future_body__7983.invoke(queue.clj:32) [cyanite-0.5.1-standalone.jar:na]
	at com.climate.claypoole.impl$binding_conveyor_fn$fn__7660.invoke(impl.clj:46) [cyanite-0.5.1-standalone.jar:na]
	at clojure.lang.AFn.applyToHelper(AFn.java:152) [cyanite-0.5.1-standalone.jar:na]
	at clojure.lang.AFn.applyTo(AFn.java:144) [cyanite-0.5.1-standalone.jar:na]
	at clojure.lang.AFunction$1.doInvoke(AFunction.java:29) [cyanite-0.5.1-standalone.jar:na]
	at clojure.lang.RestFn.invoke(RestFn.java:397) [cyanite-0.5.1-standalone.jar:na]
	at clojure.lang.AFn.call(AFn.java:18) [cyanite-0.5.1-standalone.jar:na]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [na:1.8.0_20]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180) [na:1.8.0_20]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293) [na:1.8.0_20]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [na:1.8.0_20]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [na:1.8.0_20]
	at java.lang.Thread.run(Thread.java:745) [na:1.8.0_20]
WARN [2015-07-28 15:42:00,185] claypoole-1-3 - io.cyanite.engine.queue nil original exception

**Comment by pyr** [comment]
@joshpollara this is due to your schema not being ready for this version of cyanite. You need the schema available in `doc/schema.cql`

**Comment by joshpollara** [comment]
Yep I have the new schema.

**Comment by joshpollara** [comment]
I take that back. I imported the schema again and all is well. Thanks so much for the help.

**Comment by pyr** [comment]
@joshpollara no worries, glad it could be resolved quickly.

**Comment by danielsand** [comment]
Hey @pyr ! 

Thanks a lot for the input. I will test this tomorrow when im back at the office desk :)
and @joshpollara thanks for your input - im going down the same road currently. 
will help me to get stuff straight tomorrow :)

**Comment by danielsand** [comment]
Works !
@pyr question:

What are the config options to change the port and listening host for the carbon listener ?

Currently its 2002 and 127.0.0.1 which is not helping me at all and i dont want to create a 3rd wheel to proxy this through something like haproxy/nginx.

**Comment by pyr** [comment]
Hi @danielsand,

Great to hear. The options are `host` and `port` respectively. I'll switch the ports later today to the "standard" carbon/pickle ports.

Cheers !

**Comment by mpenet** [comment]
@pyr FYI I modified alia to throw early in that case, you can get it in 2.7.2

**Comment by pyr** [comment]
@mpenet I'll definitely switch to that.

**Comment by danielsand** [comment]
Hey @pyr 

so:
```
input:
  - type: carbon
api:
  port: 8080
carbon:
  host: "0.0.0.0"
  port: "2003"
```
doesn't do the trick
either does:
```
input:
  - type: carbon
    port: "2003"
    host: "0.0.0.0"
api:
  port: 8080
```

both starts without error but doesnt start the carbon listener:
```
tcp        0      0 0.0.0.0:8080            0.0.0.0:*               LISTEN      19834/java
```

**Comment by pyr** [comment]
You'll want an integer port there: 

```yaml
input:
  - type: carbon
    host: "0.0.0.0"
    port: 2003
```
