### ISSUE TITLE
while scanning a double-quoted scalar; found unknown escape character

### ISSUE THREAD

**Issue by szop85** [pyr/cyanite#133]
Hey,

I'm using the master example configuration .yaml from doc/cyanite.yaml. Guess following line is producing an error:

```
engine:
  rules:
    "web.*\.cpu": [ "5s:1h", "30s:1d" ]
    default: [ "5s:1h" ]
```
```
10:38:00.815 [main] WARN  io.cyanite - uncaught exception
org.yaml.snakeyaml.scanner.ScannerException: while scanning a double-quoted scalar; found unknown escape character .(46)
```

Cheers,
Szop
