### ISSUE TITLE
extra configuration file for cassandra

### ISSUE THREAD

**Issue by tobiasthurow** [pyr/cyanite#141]
Hi, i would like to specify cassandra configurations in an extra config file to seperate database configuration from application configuration. Therefore it would be nice to import more than one config file.
Could you add either the support for giving additional files as parameters to the application or to include them in the existing one?

**Comment by pyr** [comment]
Hi @tobiasthurow,

Can you paste here a collection of mock configuration files as you would expect them. I fail to see the use-case for now.

**Comment by tobiasthurow** [comment]
There are several applications running with cassandra so the use would be to collect all these configurations in a single directory. On the other side the application based configuration is located in an other directory.

In one config there would be the information about the functions it provides:
```
carbon:
  host: "0.0.0.0"
  port: 2003
  rollups:
    - 10s:1d
    - 60s:14d
    - 10m:60d
    - 30m:180d
    - 1h:1y
    - 12h:2y
    - 1d:3y
http:
  host: "0.0.0.0"
  port: 18080
logging:
  overrides:
    io.cyanite: info
  level: info
  console: false
  files:
    - "/log/cyanite/cyanite.log"
```

In an other config cassandra data would be defined:
```
store:
  cluster:
    - "host1"
    - "host2"
    - "host3"
    - "host4"
  keyspace: 'metric'
  username: "cyanite"
  password: "xxxxxxxxx"
  chan_size: 10000
  batch_size: 50
```
