### ISSUE TITLE
interval resolutions issue

### ISSUE THREAD

**Issue by hryamzik** [pyr/cyanite#150]
I've taken resolutions from grafana source code and put the my cyanite config:

```yaml
engine:
  rules:
    default:
      - "1s:5m"
      - "10s:15m"
      - "1m:30m"
      - "1m:1h"
      - "2m:6h"
      - "5m:12h"
      - "10m:24h"
      - "30m:2d"
      - "1h:7d"
      - "1d:30d"
```

And once I zoom out to ```6h``` the data is empty. So I had to put ```1m``` for all the intervals higher than ```6h``` and it does slow down the UI.

I suppose this issue should be represented in #136 testing...
