### ISSUE TITLE
Cassandra index super slow

### ISSUE THREAD

**Issue by luxifr** [pyr/cyanite#156]
I gave the cassandra index a try and it seems super slow... it takes about a second for a path query, which is way too high for any meaningful use...

how do I debug this?

**Comment by TheElectricCapybara** [comment]
Confirming issues with Cassandra index performance, it appears to have big issues resolving wildcards as well.

**Comment by genericgithubuser** [comment]
The new cassandra index is showing a second to few second delay here as well.  We are trying to get this spun up to support a fairly decent sized production instance, so this poses a bit of a problem since we can not go live like this.  Is the long term plan to continue to support elasticsearch as an index option?  If so, we will revert to the previous version we were testing against and continue to use elastic if the expectation is that this will be a viable configuration in future builds.  If the plan for the stable release is to do away with the elasticsearch option, then we won't go the revert route since it'd be a temporary option.  
For anyone getting good cassandra index performance, were there specific tweaks you had to make to get this to play nicely.  Just testing this with data from 1,500 hosts with an average of 30 datapoints per against a 3 node cassandra cluster is showing the performance hit, so any tricks are appreciated.  Yes, much of it will be implementation specific, but any tweaks others have had to make for this would still be helpful to be aware of.

**Comment by eckardt** [comment]
We also found that the reads from the cassandra index are slow. Our testing setup is a single server with HDD, storing ~30000 metric paths.

There is one query for getting paths matching a given pattern which is taking especially long: https://github.com/pyr/cyanite/blob/5cdda22246f4725d9fc1e44e504efcf305c70b1c/src/io/cyanite/index/cassandra.clj#L30

One tweak that helped us improve the read performance for this particular query is to enable row caching in Cassandra: Set `row_cache_size_in_mb` in `cassandra.yaml` to something suitable (the default is `0` which disables row caching) and change the caching configuration for the `metric.path` table: `ALTER TABLE metric.path WITH caching = {'keys': 'ALL', 'rows_per_partition': '10'};`

Another tweak we tried is to cache the results of these queries in-memory for a couple of seconds. I pushed the necessary changes here: https://github.com/eckardt/cyanite/tree/memoize-matches-in-index
This is rather quick and dirty, but makes the cassandra index usable for us.

**Comment by rsvancara** [comment]
Any resolution on this?  Really a show stopper for us.

**Comment by jippi** [comment]
tried Cassandra TWCS ? ( https://github.com/jeffjirsa/twcs )

**Comment by rsvancara** [comment]
How will this help slow searches.  Does it provide an indexed search??

**Comment by aww-yiss** [comment]
Part of the challenge I've experienced here seems to be that under prod load with a volume of high cardinally metrics (~15 million unique metrics/min), it seems the ability to manage the index get pushed into old gen of the heap, and then the jvm spends a lot of CPU time of its time trying to keep up with the indexing. 

Some details for reference, hopefully some useful:

cyanite.yaml
```yaml
index:
  type: cassandra
  options:
    cluster: ["node1fqdn", "node2fqdn"]
    keyspace: metric
logging:
  level: info
  console: false
  files:
    - '/var/log/cyanite/cyanite.log'
input:
  - type: carbon
    host: '0.0.0.0'
    port: 2013
store:
  cluster: ["node1fqdn", "node2fqdn"]
    keyspace: 'metric'
api:
  host: '10.0.0.10'
  port: 8080
queues:
  defaults:
    ingestq:
      pool-size: 50
      queue-capacity: 5000000
    writeq:
      pool-size: 50
      queue-capacity: 5000000
engine:
  rules:
    default: [ "1m:90d" ]
```


Oracle Java 1.8.60 options
```
java -server -ea -Xms8G -Xmx8G -Xloggc:/var/log/cyanite/gc.log -XX:+AlwaysPreTouch -XX:+HeapDumpOnOutOfMemoryError -XX:+OptimizeStringConcat -XX:+PrintGCApplicationStoppedTime -XX:+PrintGCDateStamps -XX:+PrintGCDetails -XX:+PrintHeapAtGC -XX:+PrintPromotionFailure –XX:+PrintTenuringDistribution -XX:+UseCompressedOops -XX:+UseFastAccessorMethods -XX:+UseConcMarkSweepGC -XX:+CMSScavengeBeforeRemark -XX:CMSMaxAbortablePrecleanTime=60000 -XX:CMSWaitDuration=30000 -XX:+UseGCLogFileRotation -XX:GCLogFileSize=10M -XX:NumberOfGCLogFiles=10 -XX:PrintFLSStatistics=1 -Dcom.sun.management.jmxremote -Dcom.sun.management.jmxremote.authenticate=false -Dcom.sun.management.jmxremote.local.only=false -Dcom.sun.management.jmxremote.port=9010 -Dcom.sun.management.jmxremote.ssl=false -jar /opt/cyanite/cyanite-0.5.1-standalone.jar -f /etc/cyanite.yaml
```

![trace](https://cloud.githubusercontent.com/assets/3112865/14184466/4c358734-f743-11e5-8adc-d21b5005092b.png)
![heap](https://cloud.githubusercontent.com/assets/3112865/14184467/4c41ea06-f743-11e5-8469-f67801fb2cac.png)


Have also tried tweaking jvm to use G1GC and adjusting heap sized up and down, as small as 1GB and up to 32GB, in all instances the same issue  is observed
