### ISSUE TITLE
Memory leak

### ISSUE THREAD

**Issue by MichaelHierweck** [pyr/cyanite#204]
Hi all,

after a while I was able to try out cyanite again.

Setup: collectd => riemann => cyanite => cassandra (graphite-api not connected yet)
Cyanite was built from source @ 017932d899a215fb45f2e2cfb79d8e9691e5a851.
Riemann forwards about 1000 metrics/s.

After some time cyanite consumes more and more CPU time (60-80% => 300-400%).
Jstat reports that a growing amount of time is consumed by GC.

With -Xms512m -Xmx512m after running for about 2 hours:
```
S0C    S1C    S0U    S1U      EC       EU        OC         OU       MC     MU    CCSC   CCSU   YGC     YGCT    FGC    FGCT     GCT
17920.0 14848.0  0.0    0.0   140800.0 140800.0  349696.0   349620.1  41600.0 41191.6 7552.0 7388.2    509   23.609  846  4152.488 4176.097
```

With -Xms1024m -Xmx1024m after running for about 2 hours: 
```
S0C    S1C    S0U    S1U      EC       EU        OC         OU       MC     MU    CCSC   CCSU   YGC     YGCT    FGC    FGCT     GCT
29696.0 30208.0  0.0    0.0   288768.0 288768.0  699392.0   699236.4  41600.0 41055.7 7552.0 7369.0    446   53.328  257  1234.774 1288.102
```

top:
```
PID USER      PR  NI    VIRT    RES    SHR S  %CPU %MEM     TIME+ COMMAND 
31808 cyanite   20   0 4747500 1.239g  18172 S 316.2 15.9 231:48.65 java                                                                                                                                                        
29428 cassand+  20   0 3116744 1.439g 138612 S  37.6 18.5 194:56.65 java                                                                                                                                                        
26268 riemann   20   0 4151404 681108  16796 S   3.0  8.3 126:06.47 java 
```

cyanite.yml:
```
engine:
  rules:
    default: [ "1m:6h", "5m:1d" ]
api:
  host: 127.0.0.1
  port: 8080
input:
  - type: carbon
    host: 127.0.0.1
    port: 2004
index:
  type: cassandra
  cluster: '127.0.0.1'
  keyspace: 'metric'
drift:
  type: agent
store:
  cluster: '127.0.0.1'
  keyspace: 'metric'
logging:
  level: info 
  console: true
  files:
    - "/var/log/cyanite/cyanite.log"
  overrides:
    io.cyanite: "debug"
```

Cyanite does not log anything in this setup.

Can I help tracking down this issue?

Any help is appreciated.  Thanks in advance.

**Comment by ifesdjeen** [comment]
Just a heapdump would be very useful, although I hope I can reproduce the issue locally with graphite stresser. I'll get to it.

**Comment by ifesdjeen** [comment]
@MichaelHierweck could you give a little more information: do you insert same metric names all the time? Are there any metrics with "dynamic" names (as we might be prone to symbol attach if metric names are constantly changing).

**Comment by MichaelHierweck** [comment]
On 30.04.2016 22:46, αλεx π wrote:
> @MichaelHierweck could you give a little more information: do you insert same metric names all the time? Are there any metrics with "dynamic" names (as we might be prone to symbol attach if metric names are constantly changing). 

About 100 hosts with 100 measuring points each which are served by
collectd every 10 seconds (6 times a minute).

The metric names are supposed to be rather static unless we add/change
hosts, add cpu-threads or network interfaces or something like that.

**Comment by MichaelHierweck** [comment]
I did a quick test this afternoon and changed to log settings:

```
engine:
  rules:
    default: [ "1m:6h", "5m:1d" ]
api:
  host: 127.0.0.1
  port: 8080
input:
  - type: carbon
    host: 127.0.0.1
    port: 2004
index:
  type: cassandra
  cluster: '127.0.0.1'
  keyspace: 'metric'
drift:
  type: agent
store:
  cluster: '127.0.0.1'
  keyspace: 'metric'
logging:
  level: error
  console: false
  files:
    - "/var/log/cyanite/cyanite.log"
```

With this slightly changed configuration I was not able to reproduce the
problem. (Currently running are long term test.)

Can the problem be related to "console: true" when cyanite is started
through the init system (and maybe the stdout channel is not connected)?

(I remember Riemann running into OOM trying to forward metrics to
cyanite but cyanite not reading from the socket. This appeared in my
setup when cyanite was not able to insert metrics into cassandra. A kind
of "endless streams with input/source but without a consumer/skink"
problem.)

**Comment by MichaelHierweck** [comment]
```
engine:
  rules:
    default: [ "1m:6h", "5m:1d" ]
api:
  host: 127.0.0.1
  port: 8080
input:
  - type: carbon
    host: 127.0.0.1
    port: 2004
index:
  type: cassandra
  cluster: '127.0.0.1'
  keyspace: 'metric'
drift:
  type: agent
store:
  cluster: '127.0.0.1'
  keyspace: 'metric'
logging:
  level: error
  console: false
  files:
    - "/var/log/cyanite/cyanite.log"
```
