### ISSUE TITLE
ability to use sum, min, max, and last

### ISSUE THREAD

**Issue by ehlerst** [pyr/cyanite#244]
Graphite allows 

```
[counts]
pattern = \.count$
xFilesFactor = 0.1
aggregationMethod = sum
```

Perhaps something like this 
```
engine:
  rules:
    "*\\.count": [ "5s:1h", "30s:1d" ]
      aggregation: "sum"
```
