### ISSUE TITLE
Old Gen constantly increasing

### ISSUE THREAD

**Issue by sokratisg** [pyr/cyanite#251]
We are currently evaluating Cyanite as our main carbon backend for production use.

Tried running latest releases which seems to deprecate Elasticsearch indexing in favor of Cassandra which actually seems pretty cool (one less dependency). All soakTest runs have been done using latest (master) release + Cassandra 3.0.7 (Datastax package).

Unfortunately it seems that we're on the same situation as described in this [issue comment](https://github.com/pyr/cyanite/issues/156#issuecomment-204036443). Constant increase of JVM's Old Gen until Cyanite becomes unresponsive.

Tried different GC scenarios, different soakTest mpm (10000 up to 30000), different heap sizes, different queue size settings in conf.yml but always the same result.

Is anyone else running Cyanite in production and if yes, what is your metric volume and your setup settings?

**Comment by ifesdjeen** [comment]
We know installations that serve ~60K metrics per second on ingest side. 

3.0.7 wouldn't really work with Cyanite as we require more recent Cassandra for index (starting with 3.5, with SASI) and in-memory index won't really work exactly due to the promotion problem you have described.

I assume you're running in-memory index, is that right?

**Comment by sokratisg** [comment]
Actually sorry for the typo, I am testing Cyanite with Cassandra **3.7**.

Bellow is the cyanite configuration I've been using so far:
```
logging:
  level: debug
  console: true
  files:
    - "/opt/cyanite/log/cyanite.log"
  overrides:
    io.cyanite: "debug"

drift:
  type: no-op

input:
  - type: "carbon"
    port: 2003
    host: 127.0.0.1

api:
  port: 8080
  host: 0.0.0.0

store:
  keyspace: "metric"
  cluster: 127.0.0.1

index:
  type: cassandra
  cluster: 127.0.0.1

queues:
  defaults:
    ingestq:
      pool-size: 100
      queue-capacity: 2000000
    writeq:
      pool-size: 100
      queue-capacity: 2000000

engine:
  rules:
    '^carbon\..*': [ "10s:1d", "5m:7d", "15m:30d" ]
    default: [ "60s:1d" ]
```

And here is how I start cyanite
```
java \
  -server \
  -ea \
  -Xms2G \
  -Xmx2G \
  -XX:+UseCompressedOops \
  -XX:+UseFastAccessorMethods \
  -Djava.net.preferIPv4Stack=true \
  -Xloggc:/opt/cyanite/log/gc.log \
  -XX:+PrintGCDetails \
  -XX:+PrintGCDateStamps \
  -XX:+PrintHeapAtGC \
  -XX:+PrintTenuringDistribution \
  -XX:+PrintGCApplicationStoppedTime \
  -XX:+PrintPromotionFailure \
  -XX:+UseGCLogFileRotation \
  -XX:NumberOfGCLogFiles=5 \
  -XX:GCLogFileSize=10M \
  -Dcom.sun.management.jmxremote \
  -Dcom.sun.management.jmxremote.port=9999 \
  -Dcom.sun.management.jmxremote.rmi.port=9999 \
  -Dcom.sun.management.jmxremote.ssl=false \
  -Dcom.sun.management.jmxremote.authenticate=false \
  -XX:+UseG1GC \
  -XX:MaxGCPauseMillis=200 \
  -XX:ParallelGCThreads=8 \
  -XX:ConcGCThreads=8 \
  -XX:+AlwaysPreTouch \
  -jar /opt/cyanite/bin/cyanite-0.5.1-standalone.jar \
  -f /opt/cyanite/etc/config.yml
```
