### ISSUE TITLE
Cyanite does not return absolute time range when it out of first resolution

### ISSUE THREAD

**Issue by avneradania** [pyr/cyanite#281]
When zooming graph in Grafana, from day 29 and later, there are no data points returned and see an empty graph.
Relative time "Last X days/hours" working fine.
Absolute time inside range of first resolution, which in our case is **1m:4w**, working fine.
When trying to get data from absolute time later than last 4 weeks, we get no data points and seeing empty graph.
Are you familiar with such behavior? 

cyanite.yaml:
```
engine:
 rules: 
  cyanite.*: ['10s:1d', '1m:4w', '1h:1y']
  default: ['1m:4w', '1h:1y']
```

Examples:
Working POST /render(older 4 weeks):
target=AIO.DIAG.diag2.cpu.cpu.idle&from=1503888311&until=1504007603&format=json&maxDataPoints=640

Non working POST /render(later than 4 weeks):
target=AIO.DIAG.diag2.cpu.cpu.idle&from=1501626994&until=1501686700&format=json&maxDataPoints=640
