### ISSUE TITLE
Poor performance when retrieving metrics on large dataset

### ISSUE THREAD

**Issue by addisonj** [pyr/cyanite#34]
When retrieving metrics the response time is quite slow.

I have about 8 million metrics, each one being updated about once every 60 seconds. This come out to about 600 writes/sec according to opscenter with average write latencies significantly less than 1 ms, the cassandra clusters seems to have no trouble keeping up.

However, when hitting the API endpoint with a request that retrieves the last hour of metrics, it takes about 4 or 5 seconds to get the data. Often times it can be much worse and results in timeouts from the graphite-web frontend where the graphs fail to render.

Looking at opscenter, the read latencies don't seem to go above a few milliseconds, and the average read latency as reported by nodetool is just over 6ms.

Any clues as to where the bottleneck might be?

I have one cyanite being used just for writes, another just for reads, but it doesn't seem to make too big a difference.

Here is my config:

```
carbon:
  host: "0.0.0.0"
  port: 2003
  rollups:
    - period: 60480
      rollup: 10
    - period: 105120
      rollup: 600
http:
  host: "0.0.0.0"
  port: 8080
logging:
  level: info
  console: true
store:
  cluster: 'mycluster.com'
  keyspace: 'metric'
```
