### ISSUE TITLE
Problems with Cyanite configuration

### ISSUE THREAD

**Issue by ricardmestre** [pyr/cyanite#67]
Hi everyone,

We are working with Cyanite to store metrics in Cassandra, store a cache in Elasticsearch, and read them through Graphite-web, all of it in a multiple node cluster. After a upgrade of Cassandra to a 2.1 version, and Cyanite to the  0.1.3 version, we have problems with Cyanite configuration. When we want to view the metrics, the Graphite-web doesn't find them.  

cyanite.yaml:
```
carbon:
  host: "192.168.150.111"
  port: 2003
  rollups:
   - "60s:30d"
   - "5m:180d"
   - "1h:300d"
   - "1d:1y"

http:
  host: "192.168.150.111"
  port: 8080

logging:
  level: debug
  console: true
  files:
    - "/var/log/cyanite.log"

store:
  cluster: 'localhost'
  keyspace: 'metric'

index:
  use: "io.cyanite.es_path/es-native" 
  index: "my_paths" #defaults to "cyanite_paths"
  host: "localhost" # defaults to localhost
  port: 9300 # defaults to 9300
  cluster_name: "es_4_cyanite" #REQUIRED! this is specific to your cluster and has no sensible default
```
/var/log/cyanite.log:

ERROR [2014-10-13 11:06:36,034] async-dispatch-27 - io.cyanite.es_path - No node available
org.elasticsearch.client.transport.NoNodeAvailableException: No node available
        at org.elasticsearch.client.transport.TransportClientNodesService.execute(TransportClientNodesService.java:196)
        at org.elasticsearch.client.transport.support.InternalTransportClient.execute(InternalTransportClient.java:94)
        at org.elasticsearch.client.support.AbstractClient.get(AbstractClient.java:172)
        at org.elasticsearch.client.transport.TransportClient.get(TransportClient.java:375)
        at clojurewerkz.elastisch.native$get.invoke(native.clj:63)
        at clojurewerkz.elastisch.native.document$get.invoke(document.clj:136)
        at clojurewerkz.elastisch.native.document$present_QMARK_.invoke(document.clj:164)
        at clojure.core$partial$fn__4328.invoke(core.clj:2503)
        at io.cyanite.es_path$es_native$reify__5158$fn__5302$state_machine__4698__auto____5303$fn__5305.invoke(es_path.clj:219)
        at io.cyanite.es_path$es_native$reify__5158$fn__5302$state_machine__4698__auto____5303.invoke(es_path.clj:217)
        at clojure.core.async.impl.ioc_macros$run_state_machine.invoke(ioc_macros.clj:940)
        at clojure.core.async.impl.ioc_macros$run_state_machine_wrapped.invoke(ioc_macros.clj:944)
        at clojure.core.async.impl.ioc_macros$take_BANG_$fn__4714.invoke(ioc_macros.clj:953)
        at clojure.core.async.impl.channels.ManyToManyChannel$fn__1714.invoke(channels.clj:102)
        at clojure.lang.AFn.run(AFn.java:22)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)

Do you have an idea of what is going wrong? Is the configuration correct? At least in the previous version this works fine.

Thank you very much!
