### ISSUE TITLE
cyanite always logs with level debug

### ISSUE THREAD

**Issue by stdweird** [pyr/cyanite#95]
whatever i seem to try, cyanite keeps logging with loglevel debug (which is a lot).

i tried increasing the level to anything but debug, or removing the level altogether (default should be info, right?)

i'm using latest master, cyanite is running via
```bash
/usr/lib/jvm/jre-1.8.0/bin/java -Xmx2048M -Xms2048M -cp /usr/share/java/cyanite/cyanite.jar io.cyanite -q -f /etc/cyanite.yaml
```

current config
```
---
carbon:
  host: 1.2.3.4
  port: 2013
  rollups:
  - period: 60480
    rollup: 10
  - period: 105120
    rollup: 600
http:
  host: localhost
  port: 8080
index:
  batch_size: 1000
  chan_size: 10000
  index: cyanite_paths
  url: http://192.168.1.2:9200
  use: io.cyanite.es_path/es-rest
logging:
  level: info
  console: true
  files:
  - /var/log/cyanite/cyanite.log
store:
  batch_size: 80
  chan_size: 10000
  cluster: 192.168.1.2
  keyspace: metric
```
